version: "3.9"

services:

    database:
        image: postgres
        container_name: database
        restart: always
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=Valaraukar
            - POSTGRES_DB=rentx
        volumes: 
            - pgdata:/data/postgres

        
    app:
        build: .
        container_name: rentx
        ports: 
            - 3333:3333
        volumes:
            - .:/usr/app/rentx
        links: 
            - database
        depends_on:
            - database


        

volumes:
    pgdata:
        driver: local

#Comandos:
# yarn typeorm migration:create -n CreateCategories (ele cria o arquivo que vai ser chamado pelo run para criar a table)
# yarn typeorm migration:run  (roda a migration)
# yarn typeorm migration:revert (desfaz a migration)